# Settings of the plugins. (The plugins should be stored in script/plugins)

# min_filter fills in minimum value around the invalid cell.
min_filter:                                   
  enable: True                                # weather to load this plugin
  fill_nan: False                             # Fill nans to invalid cells of elevation layer.
  is_height_layer: True                       # If this is a height layer (such as elevation) or not (such as traversability)
  layer_name: "min_filter"                    # The layer name.
  extra_params:                               # This params are passed to the plugin class on initialization.
    dilation_size: 1                         # The patch size to apply
    iteration_n: 30                           # The number of iterations
# Apply smoothing.
smooth_filter:
  enable: True
  fill_nan: False
  is_height_layer: True
  layer_name: "smooth"
  extra_params:
    input_layer_name: "elevation"
# Apply inpainting using opencv
inpainting:
  enable: True
  fill_nan: False
  is_height_layer: True
  layer_name: "inpaint"
  extra_params:
    method: "ns"                           # telea or ns
# Apply smoothing for inpainted layer
erosion:
  enable: True
  fill_nan: False
  is_height_layer: False
  layer_name: "erosion"
  extra_params:
    input_layer_name: "traversability"
    dilation_size: 3
    iteration_n: 20
    reverse: True

example:                                      # Name of your filter
  type: "example"                             # Specify the name of your plugin (the name of your file name).
  enable: True                                # weather to load this plugin
  fill_nan: True                              # Fill nans to invalid cells of elevation layer.
  is_height_layer: True                       # If this is a height layer (such as elevation) or not (such as traversability)
  layer_name: "example_layer"                 # The layer name.
  extra_params:    
    input_layer_name: "smooth"                           # This params are passed to the plugin class on initialization.
    add_value: 2.0                            # Example param

sobel:
  type: "edge_detection"
  enable: True
  fill_nan: True
  is_height_layer: True
  layer_name: "sobel"
  extra_params:
    input_layer_name: "elevation"
    algo: "sobel"

prewitt:
  type: "edge_detection"
  enable: True
  fill_nan: True
  is_height_layer: True
  layer_name: "prewitt"
  extra_params:
    input_layer_name: "elevation"
    algo: "prewitt"

laplace:
  type: "edge_detection"
  enable: True
  fill_nan: True
  is_height_layer: True
  layer_name: "laplace"
  extra_params:
    input_layer_name: "elevation"
    algo: "laplace"

gaussian_laplace1:
  type: "edge_detection"
  enable: True
  fill_nan: True
  is_height_layer: True
  layer_name: "gaussian_laplace1"
  extra_params:
    input_layer_name: "elevation"
    algo: "gaussian_laplace"
    sigma: 1

gaussian_laplace3:
  type: "edge_detection"
  enable: True
  fill_nan: True
  is_height_layer: True
  layer_name: "gaussian_laplace3"
  extra_params:
    input_layer_name: "elevation"
    algo: "gaussian_laplace"
    sigma: 3

    



